depot-master/config/routes.rb
Rails.application.routes.draw do

  get 'admin' => 'admin#index'
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  resources :pictures

  resources :users

  scope '(:locale)' do
    root 'store#index'
    resources :orders
    resources :line_items
    resources :carts
    get 'store/index', as: 'store', via: :all
    resources :products do
      get :who_bought, on: :member
    end
    resources :reviews
  end

end

depot-master/app/models/cart.rb
class Cart < ActiveRecord::Base
  # Если мы уничтожим корзину, нам нужно, чтобы Rails также уничтожил
  # все связанные с ней товарные позиции.
  has_many :line_items, dependent: :destroy

  def add_product(product_id)
    current_item = line_items.find_by_product_id(product_id)
    if current_item
      current_item.quantity += 1
    else
      current_item = line_items.build(product_id: product_id)
    end
    current_item.price = Product.find(product_id).price
    current_item
  end

  def total_price
    line_items.to_a.sum {|item| item.total_price}
  end
end

depot-master/app/controllers/carts_controller.rb
# encoding: utf-8
class CartsController < ApplicationController
  # Разрешим неавторизованному юзеру создавать, обновлять и удалять корзины
  skip_before_action :authorize, only: [:create, :update, :destroy]

  before_action :set_cart, only: [:show, :edit]

  # GET /carts
  # GET /carts.json
  def index
    @carts = Cart.all
  end

  # GET /carts/1
  # GET /carts/1.json
  def show
    
    #set_cart
  end

  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts
  # POST /carts.json
  def create
    @cart = Cart.new(cart_params)

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: 'Cart was successfully created.' }
        format.json { render :show, status: :created, location: @cart }
      else
        format.html { render :new }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carts/1
  # PATCH/PUT /carts/1.json
  def update
    @cart = current_cart
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
        format.json { render :show, status: :ok, location: @cart }
      else
        format.html { render :edit }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    @cart = current_cart
    @cart.destroy
    session[:cart_id] = nil
    respond_to do |format|
      format.js
      format.html { redirect_to store_index_url }
      format.json { head :ok }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart
      @cart = Cart.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      logger.error "Попытка доступа к несуществующей корзине #{params[:id]}"
      redirect_to store_index_url, notice: "Несуществующая корзина №#{params[:id]}"
    else
      respond_to do |format|
        format.html # show.html.erb
        format.json { render json: @cart }
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cart_params
      params[:cart] || {}
    end
end

depot-master/app/helpers/carts_helper.rb
# encoding: utf-8
module CartsHelper
  # Use callbacks to share common setup or constraints between actions.
  def set_cart
    @cart = Cart.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    logger.error "Попытка доступа к несуществующей корзине #{params[:id]}"
    redirect_to store_index_url, notice: "Несуществующая корзина №#{params[:id]}"
  else
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @cart }
    end
  end
end

depot-master/app/views/carts/_cart.html.haml
%h2.cart_title= t('activerecord.models.cart')

%table
  = render(@cart.line_items)

  %tr.total_line
    %td{colspan: 2} Всего
    %td.total_cell= number_to_currency(@cart.total_price)
    %td
  %tr

= button_to t('.checkout'), new_order_path, class: 'js-checkout', method: :get
= button_to t('.empty_cart'), cart, method: :delete, remote: true

depot-master/app/views/carts/_form.html.haml
= form_for(@cart) do |f|
  - if @cart.errors.any?
    #error_explanation
      %h2
        = pluralize(@cart.errors.count, "error")
        prohibited this cart from being saved:
      %ul
        - @cart.errors.full_messages.each do |message|
          %li= message
  .actions
    = f.submit

depot-master/app/views/carts/destroy.js.haml
$(function () {
var $cart = $('#cart');
$cart.fadeOut("normal", function() {
$(this).html('').show();
});
});

depot-master/app/views/carts/edit.html.haml
%h1 Editing cart
= render 'form'
= link_to 'Show', @cart
|
= link_to 'Back', carts_path

depot-master/app/views/carts/index.html.haml
%h1 Listing carts
%table
  %thead
    %tr
      %th{:colspan => "3"}
  %tbody
    - @carts.each do |cart|
      %tr
        %td= link_to 'Show', cart
        %td= link_to 'Edit', edit_cart_path(cart)
        %td= link_to 'Destroy', cart, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Cart', new_cart_path

depot-master/app/views/carts/new.html.haml
%h1 New cart
= render 'form'
= link_to 'Back', carts_path

depot-master/app/views/carts/show.html.haml
- if notice
  %p#notice= notice

= render(@cart)